# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git base-devel zip
 
    - name: Get Lua Version
      id: get-lua-version
      run: |
        echo "::set-output name=version::5.4.3"
      shell: bash

    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      name: Download the file
      env:
          LUA_VERSION: ${{ steps.get-lua-version.outputs.version }}
      with:
        url: "http://www.lua.org/ftp/lua-${{env.LUA_VERSION}}.tar.gz"
        target: .
          
    - name: Make
      env:
        LUA_VERSION: ${{ steps.get-lua-version.outputs.version }}
      run: |
        tar zxf lua-${{env.LUA_VERSION}}.tar.gz
        cd lua-${{env.LUA_VERSION}}
        make generic
        
    - name: Zip
      shell: msys2 {0}
      run: |
        zip -j Lua.zip lua/src/lua.exe

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTIONS_REMOTE_BUILD_TOKEN }}
        file: Lua.zip
        asset_name: Lua.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Lua.exe"
        
