# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel

    - uses: actions/checkout@v2
    - run: git config --global user.email "kinbei@qq.com"
    - run: git config --global user.name "kinbei"

    - uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true
  
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      name: Download the file
      env:
          LUA_VERSION: 5.4.2
      with:
        url: "http://www.lua.org/ftp/lua-${{env.LUA_VERSION}}.tar.gz"
        target: .
          
    - name: Make
      env:
        LUA_VERSION: 5.4.2
      run: |
        tar zxf lua-${{env.LUA_VERSION}}.tar.gz
        cd lua-${{env.LUA_VERSION}}
        make mingw


    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: Binaries

    - name: Push
      env:
          LUA_VERSION: 5.4.2
      run: |
        mkdir -p Binaries
        cp lua-${{env.LUA_VERSION}}/src/*.exe Binaries/
        cp lua-${{env.LUA_VERSION}}/src/*.dll Binaries/
        git add Binaries
        git commit -m "Automated commit" -a
        git push
        
